# Generated by Django 4.2.7 on 2023-11-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='literary_genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('number_page', models.IntegerField()),
                ('number_book', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('publication_date', models.DateField()),
                ('created_at', models.DateField()),
                ('in_stock', models.BooleanField(default=False)),
                ('literary_genres', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='book.literary_genres')),
            ],
        ),
    ]
