# Generated by Django 4.2.7 on 2023-11-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='literary_genres',
            new_name='Genres',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genres'},
        ),
    ]
