# Generated by Django 4.2.7 on 2023-11-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_books_user_alter_books_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
