# Generated by Django 4.2.7 on 2023-12-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_lending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='book_lending',
            new_name='book_lend',
        ),
        migrations.RenameField(
            model_name='lending',
            old_name='user',
            new_name='user_lend',
        ),
        migrations.RemoveField(
            model_name='lending',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='literary_genres',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.genres'),
        ),
    ]
