# Generated by Django 4.2.7 on 2023-12-03 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_book_lending_lending_book_lend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='date_Lend',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
