# Generated by Django 4.2.7 on 2023-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_lending_date_lend'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='date_return',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
