# Generated by Django 4.2.7 on 2023-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_lending_date_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='date_return',
            field=models.DateField(),
        ),
    ]
