# Generated by Django 4.2.7 on 2023-12-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_lending_date_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='date_return',
        ),
    ]
